const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,opt={}){const r=await fetch('/api'+path,{credentials:'include',cache:'no-store',...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}});const d=await r.json().catch(()=>({success:false,error:'Server response invalid'}));if(!r.ok||d.success===false)throw Error(d.error||'Request failed');return d}
function toast(x){const t=$('#toast');t.textContent=x;t.style.display='block';setTimeout(()=>t.style.display='none',2500)}
async function me(){return (await api('/auth')).user}
async function menu(){const d=await api('/categories'),cats=d.categories||[],ps=cats.filter(c=>!c.parent_id),children=p=>cats.filter(c=>Number(c.parent_id)===Number(p.id));$('#desktopNav').innerHTML=ps.map(p=>{const ch=children(p);return `<div class="nav-item"><a class="nav-btn" href="/?category=${encodeURIComponent(p.slug)}">${esc(p.name)}${ch.length?' ▾':''}</a>${ch.length?`<div class="dropdown">${ch.map(c=>`<a href="/?category=${encodeURIComponent(c.slug)}">${esc(c.name)}</a>`).join('')}</div>`:''}</div>`}).join('');$('#mobileNav').innerHTML=ps.map(p=>{const ch=children(p);return `<div class="m-parent"><button data-m="${p.id}">${esc(p.name)} <span>⌄</span></button>${ch.length?`<div class="m-sub" id="m${p.id}">${ch.map(c=>`<a href="/?category=${encodeURIComponent(c.slug)}">${esc(c.name)}</a>`).join('')}</div>`:''}</div>`}).join('');document.querySelectorAll('[data-m]').forEach(b=>b.onclick=()=>$('#m'+b.dataset.m)?.classList.toggle('open'))}
async function render(){await menu();const u=await me();$('#authTop').innerHTML=u?`<a href="/account.html">${esc(u.name)}</a> <a href="/account.html">खाता</a>`:`<a href="/login.html">Login / Register</a>`;$('#year').textContent=new Date().getFullYear();$('#searchBtn').onclick=()=>{const q=$('#search').value.trim();location.href=q?`/?q=${encodeURIComponent(q)}`:'/'};const p=new URLSearchParams(location.search),slug=p.get('slug'),cat=p.get('category'),q=p.get('q');if(slug)return article(slug);return home(cat,q)}
async function home(cat,q){const d=await api('/news?limit=18'+(cat?'&category_slug='+encodeURIComponent(cat):'')+(q?'&q='+encodeURIComponent(q):''));const n=d.news||[];$('#view').innerHTML=`<section class="hero"><div class="hero-grid"><div class="hero-card">${n[0]?`<img src="${esc(n[0].image_url||'')}" onerror="this.style.display='none'"><div class="hero-body"><span class="tag">${esc(n[0].category_name||'समाचार')}</span><h1 class="hero-title"><a href="/?slug=${encodeURIComponent(n[0].slug)}">${esc(n[0].title)}</a></h1><p class="muted">${esc(n[0].summary||'')}</p></div>`:'<div class="hero-body">एखन कोनो समाचार उपलब्ध नहि अछि।</div>'}</div><div class="card pad"><h3>पाठक सदस्यता</h3><p class="muted">विशेष सुविधा लेल account बनाउ।</p><a class="btn btn-primary" href="/account.html">सदस्यता देखू</a></div></div></section><h2 class="section-title">${q?'खोज परिणाम':cat?'श्रेणी समाचार':'नवीन समाचार'}</h2><section class="news-grid">${n.map(x=>`<article class="news-card"><a href="/?slug=${encodeURIComponent(x.slug)}"><img class="news-img" src="${esc(x.image_url||'')}" onerror="this.style.display='none'"><div class="news-body"><span class="tag">${esc(x.category_name||'समाचार')}</span><div class="news-title">${esc(x.title)}</div><p class="muted">${esc(x.summary||'')}</p><small class="muted">${esc(x.author_name||'समाचार डेस्क')} · ${esc(x.views||0)} views</small></div></a></article>`).join('')}</section>`}
async function article(slug){const d=await api('/news?slug='+encodeURIComponent(slug)),n=d.news;$('#view').innerHTML=`<article class="article"><span class="tag">${esc(n.category_name||'समाचार')}</span><h1>${esc(n.title)}</h1><div class="muted">लेखक: ${esc(n.author_name||'समाचार डेस्क')} · ${esc(n.published_at||'')}</div>${n.image_url?`<img src="${esc(n.image_url)}">`:''}<p class="article-content">${esc(n.content)}</p><div class="engage" id="engage"><button class="btn btn-light" id="likeBtn">♡ Like</button><button class="btn btn-light" id="bookBtn">🔖 Bookmark</button></div><section class="comments"><h2>टिप्पणी</h2><div id="commentList">लोड भ' रहल अछि...</div><div id="commentForm"></div></section></article>`;await loadEngagement(n.id);await loadComments(n.id);const u=await me();$('#commentForm').innerHTML=u?`<textarea id="commentBody" class="input" rows="4" placeholder="अपन टिप्पणी लिखू..."></textarea><button class="btn btn-primary" id="commentBtn">टिप्पणी भेजू</button>`:`<p class="muted"><a href="/login.html">Login</a> क' क' टिप्पणी करू।</p>`;$('#commentBtn')?.addEventListener('click',async()=>{try{await api('/comments?news_id='+n.id,{method:'POST',body:JSON.stringify({body:$('#commentBody').value})});$('#commentBody').value='';toast('टिप्पणी review लेल भेजल गेल।')}catch(e){toast(e.message)}})}
async function loadEngagement(id){try{const d=await api('/engagement?news_id='+id);$('#likeBtn').textContent=`${d.liked?'♥':'♡'} Like (${d.likes})`;$('#bookBtn').textContent=`🔖 ${d.bookmarked?'Saved':'Bookmark'}`;$('#likeBtn').onclick=async()=>{try{await api('/engagement?news_id='+id,{method:'POST',body:JSON.stringify({type:'like'})});loadEngagement(id)}catch(e){toast(e.message)}};$('#bookBtn').onclick=async()=>{try{await api('/engagement?news_id='+id,{method:'POST',body:JSON.stringify({type:'bookmark'})});loadEngagement(id)}catch(e){toast(e.message)}}}catch(e){}}
async function loadComments(id){try{const d=await api('/comments?news_id='+id),cs=d.comments||[];$('#commentList').innerHTML=cs.length?cs.map(c=>`<div class="comment"><b>${esc(c.name)}</b><small class="muted"> ${esc(c.created_at)}</small><p>${esc(c.body)}</p></div>`).join(''):'<p class="muted">अखन कोनो approved टिप्पणी नहि अछि।</p>'}catch(e){$('#commentList').textContent=e.message}}
$('#mobileToggle').onclick=()=>$('#mobileNav').classList.toggle('open');render().catch(e=>$('#view').innerHTML=`<div class="panel">${esc(e.message)}</div>`);
