const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,opt={}){const r=await fetch('/api'+path,{credentials:'include',cache:'no-store',...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}});const d=await r.json().catch(()=>({success:false,error:'Server response invalid'}));if(!r.ok||d.success===false)throw Error(d.error||'Request failed');return d}
function toast(x){const t=$('#toast');t.textContent=x;t.style.display='block';setTimeout(()=>t.style.display='none',2500)}
async function me(){return (await api('/auth')).user}
async function menu(){const d=await api('/categories');const cats=d.categories||[];const parents=cats.filter(c=>!c.parent_id);const children=p=>cats.filter(c=>Number(c.parent_id)===Number(p.id));$('#desktopNav').innerHTML=parents.map(p=>{const ch=children(p);return `<div class="nav-item"><a class="nav-btn" href="/?category=${encodeURIComponent(p.slug)}">${esc(p.name)}${ch.length?' ▾':''}</a>${ch.length?`<div class="dropdown">${ch.map(c=>`<a href="/?category=${encodeURIComponent(c.slug)}">${esc(c.name)}</a>`).join('')}</div>`:''}</div>`}).join('');$('#mobileNav').innerHTML=parents.map(p=>{const ch=children(p);return `<div class="m-parent"><button data-m="${p.id}">${esc(p.name)} <span>⌄</span></button>${ch.length?`<div class="m-sub" id="m${p.id}">${ch.map(c=>`<a href="/?category=${encodeURIComponent(c.slug)}">${esc(c.name)}</a>`).join('')}</div>`:''}</div>`}).join('');document.querySelectorAll('[data-m]').forEach(b=>b.onclick=()=>$('#m'+b.dataset.m)?.classList.toggle('open'))}
async function render(){await menu();const u=await me();$('#authTop').innerHTML=u?`<a href="/account.html">${esc(u.name)}</a>`:`<a href="/login.html">Login / Register</a>`;$('#year').textContent=new Date().getFullYear();const q=new URLSearchParams(location.search);const slug=q.get('slug'),cat=q.get('category'),search=q.get('q');if(slug)return article(slug);return home(cat,search)}
async function home(cat,search){const d=await api('/news?limit=18'+(cat?'&category_slug='+encodeURIComponent(cat):'')+(search?'&q='+encodeURIComponent(search):''));const n=d.news||[];let h=`<section class="hero"><div class="hero-grid"><div class="hero-card">${n[0]?`<img src="${esc(n[0].image_url||'')}" onerror="this.style.display='none'"><div class="hero-body"><span class="tag">${esc(n[0].category_name||'समाचार')}</span><h1 class="hero-title"><a href="/?slug=${encodeURIComponent(n[0].slug)}">${esc(n[0].title)}</a></h1><div class="muted">${esc(n[0].summary||'')}</div></div>`:'<div class="hero-body">एखन समाचार उपलब्ध नहि अछि।</div>'}</div><div class="card" style="padding:18px"><h3>पाठक सदस्यता</h3><p class="muted">विशेष सामग्री आ सदस्य सुविधा लेल account बनाउ।</p><a class="btn btn-primary" href="/account.html">सदस्यता देखू</a></div></div></section><h2 class="section-title">नवीन समाचार</h2><section class="news-grid">${n.map(x=>`<article class="news-card"><img class="news-img" src="${esc(x.image_url||'')}" onerror="this.style.display='none'"><div class="news-body"><span class="tag">${esc(x.category_name||'समाचार')}</span><div class="news-title"><a href="/?slug=${encodeURIComponent(x.slug)}">${esc(x.title)}</a></div><p class="muted">${esc(x.summary||'')}</p></div></article>`).join('')}</section>`;$('#view').innerHTML=h}
async function article(slug){const d=await api('/news?slug='+encodeURIComponent(slug));const n=d.news;$('#view').innerHTML=`<article class="article"><span class="tag">${esc(n.category_name||'समाचार')}</span><h1>${esc(n.title)}</h1><div class="muted">लेखक: ${esc(n.author_name||'समाचार डेस्क')} · ${esc(n.published_at||'')}</div>${n.image_url?`<img src="${esc(n.image_url)}">`:''}<p class="article-content">${esc(n.content)}</p></article>`}
$('#mobileToggle').onclick=()=>$('#mobileNav').classList.toggle('open');render().catch(e=>{$('#view').innerHTML=`<div class="panel">${esc(e.message)}</div>`});
